name: Workflow

on: [push]

jobs:
  PrimeiroJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Executando o STEP1
        run: |
          echo Esse processo carrega uma mensagem
          echo basica para entender o workflow
