name: Workflow

on: [push]

jobs:
  PrimeiroJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Python script
        run: python your_script.py
